<?php


namespace Database\Seeders;


use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Skill;


class SkillSeeder extends Seeder
{
    public function run(): void
    {
        $skills = [
            // ===== COMMON SOFT SKILLS (100) =====
            'Communication',
            'Teamwork',
            'Problem Solving',
            'Critical Thinking',
            'Time Management',
            'Adaptability',
            'Leadership',
            'Creativity',
            'Work Ethic',
            'Decision Making',
            'Attention to Detail',
            'Collaboration',
            'Interpersonal Skills',
            'Conflict Resolution',
            'Active Listening',
            'Empathy',
            'Self-Motivation',
            'Accountability',
            'Emotional Intelligence',
            'Stress Management',
            'Professionalism',
            'Negotiation',
            'Presentation Skills',
            'Public Speaking',
            'Multitasking',
            'Resilience',
            'Flexibility',
            'Self-Discipline',
            'Integrity',
            'Patience',
            'Confidence',
            'Coaching',
            'Mentoring',
            'Cultural Awareness',
            'Dependability',
            'Resourcefulness',
            'Goal Setting',
            'Decision Analysis',
            'Analytical Thinking',
            'Open-Mindedness',
            'Adaptability to Change',
            'Persuasion',
            'Customer Focus',
            'Team Leadership',
            'Collaboration Across Teams',
            'Constructive Feedback',
            'Positive Attitude',
            'Ethical Judgment',
            'Workplace Etiquette',
            'Writing Skills',
            'Critical Reading',
            'Problem Analysis',
            'Negotiation Skills',
            'Networking',
            'Innovation',
            'Strategic Thinking',
            'Curiosity',
            'Delegation',
            'Listening Comprehension',
            'Conflict Management',
            'Confidence Building',
            'Team Coordination',
            'Time Prioritization',
            'Professional Communication',
            'Task Planning',
            'Decision Evaluation',
            'Reliability',
            'Observation Skills',
            'Cooperation',
            'Adaptation to Technology',
            'Organizational Awareness',
            'Client Relations',
            'Self-Reflection',
            'Continuous Learning',
            'Process Improvement',
            'Diplomacy',
            'Account Management',
            'Motivational Skills',
            'Judgment',
            'Productivity',
            'Team Encouragement',
            'Leadership Communication',
            'Self-Awareness',
            'Goal-Oriented Mindset',
            'Confidence Under Pressure',
            'Stress Tolerance',
            'Cross-Functional Collaboration',
            'Feedback Reception',
            'Clarity in Communication',
            'Meeting Facilitation',
            'Mentoring Peers',
            'Adaptation in Crisis',
            'Professional Writing',
            'Listening and Clarifying',
            'Constructive Criticism',
            'Workload Management',
            'Innovation in Tasks',
            'Customer Engagement',
            'Self-Improvement',
            'Quality Focus',


            // ===== IT & COMPUTER SCIENCE (150) =====
            'PHP',
            'Laravel',
            'JavaScript',
            'Python',
            'MySQL',
            'HTML',
            'CSS',
            'React',
            'Vue.js',
            'Node.js',
            'Express.js',
            'MongoDB',
            'Java',
            'C++',
            'C#',
            'Bootstrap',
            'Tailwind CSS',
            'RESTful APIs',
            'AJAX',
            'JSON',
            'Git',
            'GitHub',
            'Version Control',
            'OOP Concepts',
            'MVC Framework',
            'Database Design',
            'UML Diagramming',
            'System Analysis',
            'Linux',
            'Windows Server',
            'Networking Basics',
            'Cybersecurity',
            'Penetration Testing',
            'Network Configuration',
            'Data Structures',
            'Algorithms',
            'Computer Architecture',
            'Operating Systems',
            'Software Engineering',
            'Web Development',
            'Mobile App Development',
            'Flutter',
            'React Native',
            'Kotlin',
            'Android Studio',
            'Firebase',
            'AWS',
            'Azure',
            'Cloud Computing',
            'DevOps',
            'Docker',
            'CI/CD',
            'API Integration',
            'Web Security',
            'SSL Configuration',
            'DNS Management',
            'IT Troubleshooting',
            'Technical Support',
            'Helpdesk Operations',
            'Computer Assembly',
            'Hardware Maintenance',
            'Software Installation',
            'System Administration',
            'Database Administration',
            'Information Security',
            'Data Privacy',
            'Network Troubleshooting',
            'LAN/WAN Configuration',
            'VPN Setup',
            'IT Documentation',
            'Technical Writing',
            'Software Testing',
            'Unit Testing',
            'QA Testing',
            'Bug Tracking',
            'Agile Methodology',
            'Scrum',
            'Sprint Planning',
            'Kanban',
            'System Implementation',
            'API Testing',
            'Postman',
            'Swagger',
            'IT Project Management',
            'SDLC',
            'UAT Testing',
            'Version Deployment',
            'Code Debugging',
            'Database Optimization',
            'SQL Queries',
            'Triggers and Stored Procedures',
            'Frontend Design',
            'UI/UX Principles',
            'Wireframing',
            'Prototyping',
            'Figma',
            'Adobe XD',
            'Responsive Design',
            'Cross-Browser Compatibility',
            'Performance Tuning',
            'Cloud Storage Management',
            'Networking Tools',
            'Firewall Configuration',
            'Encryption Standards',
            'IT Compliance',
            'Ethical Hacking',
            'IT Risk Management',
            'Incident Response',
            'Log Monitoring',
            'IT Asset Management',
            'Software Licensing',
            'Technical Documentation',
            'Programming Logic',
            'Data Analysis',
            'Python Pandas',
            'Numpy',
            'Data Visualization',
            'Power BI',
            'Machine Learning Basics',
            'TensorFlow',
            'AI Concepts',
            'Chatbot Development',
            'Natural Language Processing',
            'Computer Vision',
            'Robotics Basics',
            'Embedded Systems',
            'Arduino Programming',
            'IoT Fundamentals',
            'Raspberry Pi',
            'API Authentication',
            'OAuth',
            'Web Hosting',
            'FTP Management',
            'Domain Configuration',
            'Server Monitoring',
            'Backup and Restore',
            'Network Security Policies',
            'IT Procurement',
            'IT Support Ticketing',
            'Customer Technical Support',
            'Data Recovery Techniques',
            'IT Compliance Standards',
            'Programming Documentation',
            'Algorithm Optimization',
            'Memory Management',
            'Code Refactoring',
            'Version Rollback',
            'Mobile UI Testing',
            'Cross-Platform Development',


            // ===== ACCOUNTANCY & BUSINESS (150) =====
            'Financial Accounting',
            'Cost Accounting',
            'Managerial Accounting',
            'Auditing',
            'Taxation',
            'Bookkeeping',
            'Payroll Management',
            'Bank Reconciliation',
            'Financial Reporting',
            'Budgeting',
            'Financial Analysis',
            'Spreadsheet Proficiency',
            'Microsoft Excel',
            'Accounting Software',
            'QuickBooks',
            'SAP Accounting',
            'Peachtree',
            'Financial Forecasting',
            'Internal Control',
            'Cash Flow Management',
            'Business Analytics',
            'Data Interpretation',
            'Business Ethics',
            'Market Research',
            'Sales Strategy',
            'Advertising',
            'Customer Relationship Management',
            'Marketing Analytics',
            'Digital Marketing',
            'SEO',
            'Social Media Marketing',
            'Brand Management',
            'Product Promotion',
            'Business Presentation',
            'Customer Service',
            'Inventory Management',
            'E-commerce Management',
            'Supply Chain',
            'Retail Operations',
            'Entrepreneurial Thinking',
            'Business Plan Development',
            'Negotiation and Sales',
            'Financial Planning',
            'Business Law',
            'Corporate Governance',
            'Risk Management',
            'Investment Analysis',
            'Stock Market Knowledge',
            'Tax Filing',
            'Auditing Standards',
            'Cost-Benefit Analysis',
            'Pricing Strategy',
            'Marketing Campaigns',
            'CRM Software',
            'Google Analytics',
            'Email Marketing',
            'Strategic Planning',
            'Market Segmentation',
            'Product Development',
            'Promotional Planning',
            'Customer Engagement',
            'Networking in Business',
            'Partnership Development',
            'Brand Storytelling',
            'Pitch Presentation',
            'Sales Forecasting',
            'Retail Management',
            'Merchandising',
            'Entrepreneurial Finance',
            'Business Model Canvas',
            'Innovation Strategy',
            'Supply Chain Analysis',
            'Procurement',
            'Quality Assurance',
            'Lean Management',
            'Six Sigma Basics',
            'Customer Feedback Analysis',
            'Financial Modelling',
            'Cash Handling',
            'Accounts Receivable',
            'Accounts Payable',
            'Financial Statement Preparation',
            'Tax Computation',
            'Profitability Analysis',
            'Managerial Decision Making',
            'Economic Analysis',
            'Feasibility Study',
            'Entrepreneurship',
            'Startup Operations',
            'Product Launch Planning',
            'Franchise Management',
            'Business Risk Analysis',
            'Leadership in Business',
            'Negotiation with Clients',
            'Sales Pitching',
            'Corporate Strategy',
            'Business Operations',
            'Marketing Mix Application',
            'Consumer Behavior Study',
            'Market Trend Analysis',
            'Business Communication',
            'Microsoft PowerPoint',
            'Office Administration',
            'Record Management',
            'Team Coordination in Business',
            'Retail Sales',
            'Advertising Design',
            'Customer Loyalty Programs',
            'Service Marketing',
            'B2B Marketing',
            'B2C Sales',
            'Supply Logistics',
            'Distribution Management',
            'Entrepreneurial Networking',
            'Microfinance Knowledge',
            'Budget Control',
            'Inventory Forecasting',
            'Business Data Management',
            'Client Prospecting',
            'Product Costing',
            'Digital Commerce',
            'CRM Reporting',
            'Investment Planning',
            'Auditing Reports',
            'Government Compliance',
            'Payroll Computation',
            'Excel Macros',
            'Financial Statement Analysis',
            'Business Intelligence Tools',
            'Profit Analysis',
            'Tax Regulation Knowledge',
            'Fund Accounting',
            'Financial Statement Reconciliation',


            // ===== EDUCATION (100) =====
            'Lesson Planning',
            'Curriculum Development',
            'Classroom Management',
            'Student Assessment',
            'Instructional Design',
            'Learning Materials Preparation',
            'Differentiated Instruction',
            'Educational Technology',
            'Lesson Delivery',
            'Pedagogical Strategies',
            'Child Development',
            'Educational Psychology',
            'Inclusive Education',
            'Special Education Awareness',
            'Class Facilitation',
            'Student Motivation',
            'Subject Mastery',
            'Teaching Aids Creation',
            'Learning Outcome Evaluation',
            'Lesson Alignment',
            'Reading Comprehension Instruction',
            'Writing Instruction',
            'Speaking Fluency Coaching',
            'Pronunciation Training',
            'Phonics Teaching',
            'Grammar Instruction',
            'Mathematics Teaching',
            'Lesson Observation',
            'Reflective Teaching',
            'Student Progress Tracking',
            'Portfolio Assessment',
            'Performance-Based Evaluation',
            'Lesson Modification',
            'Cooperative Learning',
            'Peer Tutoring',
            'Online Learning Facilitation',
            'Classroom Discipline',
            'Lesson Differentiation',
            'Scaffolding Techniques',
            'Assessment Design',
            'Learning Support Strategies',
            'Educational Research',
            'Child Behavior Management',
            'Lesson Demonstration',
            'Blended Learning',
            'Remote Instruction',
            'Cognitive Development Understanding',
            'Instructional Materials Design',
            'Test Construction',
            'Rubric Development',
            'Subject Integration',
            'Student Centered Learning',
            'Lesson Time Management',
            'Evaluation Tools Usage',
            'Parent-Teacher Communication',
            'School Event Coordination',
            'Curriculum Evaluation',
            'Educational Assessment Tools',
            'Reading Intervention',
            'Mathematical Reasoning Instruction',
            'Lesson Observation Reports',
            'Teaching Portfolio Preparation',
            'Microteaching',
            'Educational Policy Awareness',
            'Classroom Data Management',
            'Learning Environment Setup',
            'Remediation Planning',
            'Educational Measurement',
            'Online Teaching Tools',
            'Lesson Alignment to Objectives',
            'Student Guidance',
            'Language Development Support',
            'Philosophy of Education Understanding',
            'Ethics in Teaching',
            'Learning Management System',
            'Blackboard Utilization',
            'Google Classroom Usage',
            'Lesson Delivery via Zoom',
            'Engagement Strategies',
            'Performance Assessment',
            'Oral Recitation Evaluation',
            'Lesson Documentation',
            'Peer Feedback in Teaching',
            'Student Record Keeping',
            'Homeroom Management',
            'Parent Engagement',
            'Learning Styles Identification',
            'Outcome-Based Education',
            'Lesson Revision',
            'Competency Mapping',
            'Remedial Instruction',
            'Student Counseling',
            'Lesson Reflection',
            'Assessment of Learning',
            'Formative Evaluation',
            'Summative Assessment',
            'Academic Advising',
            'Teacher Professional Development',
            'Instructional Leadership',
            'Education Planning',


            // ===== PSYCHOLOGY (100) =====
            'Behavioral Assessment',
            'Counseling Skills',
            'Psychological Testing',
            'Interview Techniques',
            'Personality Assessment',
            'Psychometric Analysis',
            'Observation Techniques',
            'Data Interpretation in Psychology',
            'Case Study Development',
            'Psychological Research',
            'Experimental Design',
            'Ethical Counseling Practice',
            'Clinical Interviewing',
            'Report Writing in Psychology',
            'Statistical Analysis in SPSS',
            'Cognitive Assessment',
            'Emotional Regulation Techniques',
            'Therapeutic Communication',
            'Psychotherapy Basics',
            'Client Rapport Building',
            'Empathic Listening',
            'Crisis Intervention',
            'Conflict Mediation',
            'Behavior Modification',
            'Stress Intervention',
            'Mental Health Awareness',
            'Psychopathology Understanding',
            'Neuropsychology Basics',
            'Cognitive Psychology',
            'Social Psychology',
            'Developmental Psychology',
            'Abnormal Psychology',
            'Organizational Psychology',
            'Industrial Psychology',
            'Human Behavior Analysis',
            'Group Dynamics',
            'Workplace Motivation',
            'Emotional Intelligence Development',
            'Counseling Ethics',
            'Therapy Session Documentation',
            'Assessment Report Preparation',
            'Confidentiality Management',
            'Client Needs Evaluation',
            'Research Proposal Writing',
            'APA Formatting',
            'Interview Transcription',
            'Observation Notes Writing',
            'Intervention Planning',
            'Mental Status Examination',
            'Test Administration',
            'Scoring Psychological Tests',
            'Client Progress Evaluation',
            'Mindfulness Facilitation',
            'Self-Awareness Exercises',
            'Behavioral Charting',
            'Case Conceptualization',
            'Group Therapy Facilitation',
            'Motivational Interviewing',
            'Cognitive Behavioral Techniques',
            'Stress Debriefing',
            'Life Coaching Basics',
            'Emotional Support Skills',
            'Mental Health Advocacy',
            'Crisis Hotline Operation',
            'Therapy Scheduling',
            'Psychological Data Collection',
            'Focus Group Facilitation',
            'Counseling Documentation',
            'Psychology Research Analysis',
            'Thematic Analysis',
            'Quantitative Data Interpretation',
            'Qualitative Coding',
            'Hypothesis Testing',
            'Experimental Observation',
            'Research Ethics',
            'Literature Review Writing',
            'Client Behavior Monitoring',
            'Psychology Case Presentation',
            'Behavioral Statistics',
            'Data Visualization for Psychology',
            'Behavioral Chart Design',
            'Human Relations Management',
            'Workplace Assessment',
            'Interview Psychology',
            'Mental Health Program Coordination',
            'Rehabilitation Support',
            'Therapeutic Evaluation',
            'Client Care Coordination',
            'Psychological Education',
            'Behavioral Training Facilitation',
            'Employee Counseling',
            'Stress Counseling',
            'Emotion Recognition',
            'Nonverbal Communication Awareness',
            'Empathy Training',
            'Resilience Building',
            'Professional Counseling Language',
            'Psychology Research Documentation',
            'Behavior Observation Accuracy',
            'Therapeutic Note-Taking',
            'Human Behavior Reporting',


            // ===== ENGINEERING (100) =====
            'Circuit Design',
            'Electronics Troubleshooting',
            'Signal Processing',
            'Microcontroller Programming',
            'Arduino Systems',
            'PCB Design',
            'Electrical Wiring',
            'Soldering',
            'Instrumentation',
            'Sensors and Actuators',
            'Microprocessor Systems',
            'Digital Logic Design',
            'Analog Circuit Analysis',
            'Control Systems',
            'Power Electronics',
            'Embedded Systems Design',
            'VHDL Programming',
            'Matlab Simulation',
            'AutoCAD Electrical',
            'Engineering Drawing',
            'Technical Documentation',
            'Engineering Mathematics',
            'C Programming for Hardware',
            'PLC Programming',
            'Industrial Automation',
            'Robotics Integration',
            'Data Acquisition Systems',
            'Signal Amplification',
            'Telecommunications Basics',
            'Wireless Communication',
            'Antenna Design',
            'Transmission Lines',
            'Network Analysis',
            'Semiconductor Devices',
            'Electronic Components Testing',
            'Schematic Diagram Interpretation',
            'Breadboarding',
            'Prototype Assembly',
            'Power Distribution',
            'Renewable Energy Systems',
            'Solar Power Systems',
            'Electrical Load Calculation',
            'Energy Efficiency Design',
            'Electrical Safety Standards',
            'Instrumentation Calibration',
            'Testing and Measurement',
            'Quality Assurance in Engineering',
            'Research and Development',
            'Technical Problem Solving',
            'Project Documentation',
            'Circuit Simulation',
            'Multisim Usage',
            'Proteus Simulation',
            'PCB Layout Design',
            'Testing Equipment Handling',
            'Hardware Debugging',
            'System Integration',
            'Computer-Aided Design',
            'Schematics Drafting',
            'Hardware Assembly',
            'Power Circuit Design',
            'Wireless Systems',
            'Fiber Optic Basics',
            'Networking Hardware',
            'RF Systems',
            'Instrumentation Systems',
            'Telecom Systems',
            'Engineering Ethics',
            'Technical Presentation',
            'Industrial Safety',
            'Maintenance Planning',
            'Equipment Testing',
            'Field Installation',
            'Control Panel Design',
            'IoT Device Integration',
            'Data Logger Configuration',
            'Industrial Communication Protocols',
            'Troubleshooting Automation Systems',
            'Sensor Calibration',
            'Hardware Configuration',
            'CAD Drafting',
            'Testing Procedure Writing',
            'Blueprint Reading',
            'Signal Transmission',
            'Analog Filter Design',
            'Microchip Programming',
            'Engineering Report Writing',
            'Technical Calculation',
            'Hardware Maintenance',
            'Electrical Circuit Testing',
            'Equipment Inspection',
            'Project Cost Estimation',
            'Root Cause Analysis',
            'Preventive Maintenance',
            'Engineering Project Coordination',
            'Measurement Tools Handling',
            'Technical Diagram Preparation',
            'Industrial Circuit Assembly',
            'Electronic Device Repair',


            // ===== NURSING (100) =====
            'Patient Care',
            'Vital Signs Monitoring',
            'Medication Administration',
            'Intravenous Therapy',
            'Health Assessment',
            'Wound Care',
            'First Aid',
            'Infection Control',
            'Nursing Documentation',
            'Patient Education',
            'Clinical Observation',
            'Emergency Response',
            'Health Promotion',
            'Basic Life Support',
            'CPR',
            'Patient Admission',
            'Patient Discharge Planning',
            'Pain Assessment',
            'IV Insertion',
            'Catheter Care',
            'Oxygen Therapy',
            'Nutrition Management',
            'Oral Care',
            'Mobility Assistance',
            'Bedside Care',
            'Patient Monitoring',
            'Medication Dosage Calculation',
            'Blood Pressure Measurement',
            'Temperature Taking',
            'Pulse Monitoring',
            'Respiration Assessment',
            'Health Screening',
            'Patient Charting',
            'Hospital Sanitation',
            'Infection Prevention',
            'Nursing Ethics',
            'Confidentiality in Care',
            'Therapeutic Communication',
            'Patient Empathy',
            'Clinical Decision Making',
            'Shift Handover Reporting',
            'Ward Management',
            'Team Nursing',
            'Patient Safety',
            'Medical Record Keeping',
            'Sterile Technique',
            'Emergency Preparedness',
            'IV Line Maintenance',
            'Specimen Collection',
            'Patient Positioning',
            'Health Counseling',
            'Rehabilitation Support',
            'Health Assessment Reporting',
            'Surgical Assistance',
            'Preoperative Care',
            'Postoperative Care',
            'Medication Reconciliation',
            'Pharmacology Knowledge',
            'Health Education Materials',
            'Infection Surveillance',
            'Personal Protective Equipment Use',
            'Patient Support',
            'Vital Data Recording',
            'Care Plan Development',
            'Patient Transfer Technique',
            'Fall Prevention',
            'Nutrition Counseling',
            'Family Communication',
            'Disaster Response',
            'Community Health Nursing',
            'Maternal Care',
            'Child Care',
            'Elderly Care',
            'Palliative Care',
            'Patient Comfort Measures',
            'Basic Diagnostic Testing',
            'Blood Glucose Monitoring',
            'Urine Testing',
            'Health History Taking',
            'Diagnostic Interpretation',
            'Nursing Care Planning',
            'IV Fluid Regulation',
            'Patient Advocacy',
            'Care Coordination',
            'Public Health Awareness',
            'Record Documentation Accuracy',
            'Nursing Report Writing',
            'Medical Equipment Handling',
            'Hospital Coordination',
            'Clinical Prioritization',
            'Patient Confidentiality',
            'Emotional Support for Patients',
            'Team Collaboration in Nursing',
            'Emergency Room Support',
            'Patient Observation Notes',
            'Hygiene Maintenance',
            'Infection Control Audit',
            'Clinical Training Assistance',
            'Nursing Process Application',
            'Ethical Nursing Practice',


            // ===== CROSS-DISCIPLINARY & MODERN WORKPLACE SKILLS (Final 100) =====
            'Data Entry Accuracy',
            'Information Literacy',
            'Digital Literacy',
            'Cloud File Management',
            'Spreadsheet Reporting',
            'Presentation Design',
            'Microsoft Word Formatting',
            'PowerPoint Presentation Design',
            'Google Workspace Usage',
            'Email Communication',
            'Calendar Scheduling',
            'Document Organization',
            'Data Backup Management',
            'Typing Proficiency',
            'Remote Collaboration',
            'Online Research',
            'Professional Correspondence',
            'Virtual Meeting Etiquette',
            'Workplace Documentation',
            'Report Writing',
            'Statistical Literacy',
            'Quantitative Reasoning',
            'Research Writing',
            'Data Gathering',
            'Survey Design',
            'Questionnaire Development',
            'Research Analysis',
            'Infographic Design',
            'Technical Reporting',
            'Business Writing',
            'Proofreading',
            'Editing Documents',
            'File Management',
            'Digital Organization',
            'Presentation Pitching',
            'Online Collaboration Tools',
            'Microsoft Teams Usage',
            'Slack Communication',
            'Google Meet Coordination',
            'Zoom Meeting Facilitation',
            'Professional Email Writing',
            'Time Tracking',
            'Workflow Optimization',
            'Goal Monitoring',
            'Process Documentation',
            'Standard Operating Procedure Writing',
            'Performance Review Preparation',
            'Workplace Innovation',
            'Idea Generation',
            'Change Management',
            'Design Thinking',
            'Strategic Problem Solving',
            'Analytical Reporting',
            'KPI Monitoring',
            'Team Productivity Tracking',
            'Project Scheduling',
            'Task Delegation',
            'Resource Allocation',
            'Conflict Prevention',
            'Meeting Summarization',
            'Organizational Planning',
            'Event Planning',
            'Office Coordination',
            'Data Visualization Tools',
            'Microsoft Power BI Reporting',
            'Google Data Studio',
            'Dashboard Creation',
            'Research Documentation',
            'Survey Data Cleaning',
            'Performance Evaluation',
            'Report Presentation',
            'Data-driven Decision Making',
            'Ethical Research Practice',
            'File Version Control',
            'Document Revision Tracking',
            'Collaboration via SharePoint',
            'Content Planning',
            'Digital File Archiving',
            'Corporate Communication',
            'Professional Networking',
            'Team Collaboration Tools Usage',
            'Project Tracking Tools',
            'Asana Project Setup',
            'Trello Board Management',
            'ClickUp Task Management',
            'Workload Planning',
            'Knowledge Management',
            'Process Automation Basics',
            'Excel Dashboarding',
            'Pivot Table Creation',
            'Data Cleansing in Excel',
            'Report Proofing',
            'Productivity Tool Utilization',
            'Cross-Cultural Communication',
            'Ethical Decision Making',
            'Employee Engagement',
            'Remote Work Adaptability',
            'Career Planning',
            'Workplace Safety Awareness',
            'Professional Growth Mindset',
            'Corporate Social Responsibility Awareness',
            'Workplace Sustainability Practices',
            'Innovation Mindset',
            'Digital Collaboration',
        ];


        foreach ($skills as $skill) {
            Skill::firstOrCreate(['name' => $skill]);
        }
    }
}
